services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=theshop'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=theshop'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local