{
 "title": "Application Caches",
 "description": "Show cache sizes and hit ratios",
 "tags": [
  "micrometer",
  "spring",
  "caching"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(cache_size{application=\"$application\"}, instance)"
    }
   },
   {
    "name": "cache",
    "label": "cache",
    "query": {
     "query": "label_values(cache_size{application=\"$application\", instance=\"$instance\"}, cache)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Hit ratio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cache_gets_total{result=\"hit\",cache=\"$cache\"}[10m]))/sum(rate(cache_gets_total{cache=\"$cache\"}[10m]))",
     "legendFormat": "\"$cache\" hit ratio"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cache_size{application=\"$application\",instance=\"$instance\",cache=\"$cache\"}",
     "legendFormat": "\"$cache\" hit ratio"
    }
   ]
  },
  {
   "title": "Cache Evictions per hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cache_evictions_total{application=\"$application\",instance=\"$instance\",cache=\"$cache\"}[1h]) * 3600",
     "legendFormat": "\"$cache\" eviction rate"
    }
   ]
  },
  {
   "title": "Hit ratio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cache_gets_total{application=\"$application\", instance=\"$instance\", result=\"hit\"}[30m]) / on(cache)\n(sum by (cache) (rate(cache_gets_total{application=\"$application\", instance=\"$instance\"}[30m])))",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "graph",
   "gridPos": { "h": 18, "w": 11, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cache_size{application=\"$application\",instance=\"$instance\"}",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Cache Evictions ",
   "type": "graph",
   "gridPos": { "h": 18, "w": 13, "x": 11, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cache_evictions_total{application=\"$application\",instance=\"$instance\"}[1h])",
     "legendFormat": "{{cache}}"
    }
   ]
  }
 ]
}