global:
  scrape_interval: 1m
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: [ "postgres-exporter:9187" ]
        labels:
          namespace: 'local'

  - job_name: 'spring-boot-local'
    metrics_path: /actuator/prometheus
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          namespace: 'local'
          app: 'the-shop'

